#!/bin/bash
# Проверка проблемы с созданием мероприятий

echo "=== Инструкция для отладки ==="
echo ""
echo "1. Откройте https://kefpulse.ru/admin/dashboard"
echo "2. Откройте консоль браузера (F12 → Console)"
echo "3. Перейдите на вкладку 'Мероприятия'"
echo "4. Нажмите 'Добавить мероприятие'"
echo "5. Заполните форму:"
echo "   - Название: Test Event"
echo "   - ID зоны: luzhniki"
echo "   - Тип: concert"
echo "   - Время окончания: любая дата в будущем"
echo "6. Нажмите 'Создать мероприятие'"
echo "7. СМОТРИТЕ В КОНСОЛЬ - должны появиться логи:"
echo "   Creating event: {...}"
echo "   Response status: XXX"
echo "   Response data: {...}"
echo ""
echo "Отправьте мне ВСЕ логи из консоли"
echo ""
echo "=== Также проверьте логи сервера ==="
echo ""
tail -50 /opt/taxibot/bot.log | grep -i "event\|error\|create"
